### ISSUE TITLE
multiple_input not recognizing W A S D

### ISSUE THREAD

**Issue by shanecelis** [elm-register/bevy-input-sequence#3]
Working on the bevy v0.13 PR, and I've run into a regression. If you run the `multiple_input` example, you'll see that it won't pick up W A S D when used with ActPattern. So my optimistic code has failed in some way.

Another point to consider, when accepting gamepad buttons our events will realistically need to provide the gamepad id they came from. So I'm not sure what's the best way to unify on that. Perhaps it'd be best if key sequences and gamepad buttons were accepted as distinct things.

I'll work on a PR.

**Comment by not-elm** [comment]
Omg, I missed it.

It seems that `binary_search_by_key` is called when registering the key.

https://github.com/laysakura/trie-rs/blob/582566110e09c0404a2e561b1456bc554c932871/src/internal_data_structure/naive_trie/naive_trie.rs#L20

I do not fully understand how this library works, but here are my guesses

For example, when regisering three acts `A | B`, `C | D` and `A | E`, `A | B` and `C | D` will succeed, but `A | E` will.
This is because `A | B`.cmp(&`A | E`) returns `Ordering::Equal` and it is determined that `A | E` already exists as a node.

```
`<Key1> | <Key2>` = ActPattern::Any([Key1, Key2])
```

So, `A | B` and `A | E` must not be `Ordering::Equal`; However, doing so will cause a problem when validating key inputs...
<details>
<summary>example setup system</summary>

```rust
fn setup(mut commands: Commands) {
    // Registered successfully
    commands.spawn(
        InputSequence::new(
            MyEvent,
            [
                Act::from(KeyCode::A) | Act::from(KeyCode::C),
                Act::from(KeyCode::B) | Act::from(KeyCode::D),
            ],
        )
            .time_limit(Duration::from_secs(5)),
    );
	
    // Registered successfully
    commands.spawn(
        InputSequence::new(
            MyEvent,
            [
                Act::from(KeyCode::E) | Act::from(KeyCode::G),
                Act::from(KeyCode::F) | Act::from(KeyCode::H),
            ],
        )
            .time_limit(Duration::from_secs(5)),
    );
    
 
    commands.spawn(
        InputSequence::new(
            MyEvent,
            [
                Act::from(KeyCode::I) | Act::from(KeyCode::A), // Registered as A | C
                Act::from(KeyCode::J) | Act::from(KeyCode::K),
            ],
        )
            .time_limit(Duration::from_secs(5)),
    );
    println!("Press W D S A or north east south west to emit event.");
}
```
</details>
